name: PreMerge Check
on:
  pull-request:
    branches: [ main ]
jobs:
  setup&validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "Hello World" 
